micronaut-projects/micronaut-profiles

- service/templates/java/ControllerTest.java
The parameters passed to `asserEquals` are not in correct order.
> Switched actual and expected parameters in assert for ControllerTest.

- base/features/groovy/feature.yml
- base/features/spock/feature.yml
Fixes https://github.com/micronaut-projects/micronaut-core/issues/322
Adds some duplication between `groovy` and `spock` features, not sure there's any way to avoid that.
> Removed groovy feature dependency from spock feature - #322

- base/commands/create-bean.groovy
- base/commands/create-job.groovy
- buildSrc/build.gradle
- buildSrc/src/main/groovy/io/micronaut/gradle/profile/task/ProfileCompilerTask.groovy
- service/commands/create-client.groovy
- service/commands/create-controller.groovy
Please take a look at this PR for https://github.com/micronaut-projects/micronaut-core/issues/256 using picocli for command line parsing.
* All `create-xxx.groovy` commands now use picocli annotations
* All `create-xxx.groovy` commands now use the `SupportedLanguage` enum defined in the cli module (see PR https://github.com/micronaut-projects/micronaut-core/pull/368)
This PR should be tested together with https://github.com/micronaut-projects/micronaut-core/pull/368.
> #256 use picocli for command line parsing

- base/features/kotlin/feature.yml
This module for jackson makes mapping to Kotlin data classes substantially more convenient, I would recommend we add it to the kotlin profile, as anyone consuming APIs in kotlin will almost certainly appreciate it.
> Adds jackson object mapper module to kotlin build.gradle dependencies

- cli/features/picocli-groovy/feature.yml
- cli/features/picocli-groovy/skeleton/src/main/groovy/@defaultPackage.path@/@project.className@Command.groovy
- cli/features/picocli-java/feature.yml
- cli/features/picocli-java/skeleton/src/main/java/@defaultPackage.path@/@project.className@Command.java
- cli/features/picocli-kotlin/feature.yml
- cli/features/picocli-kotlin/skeleton/src/main/kotlin/@defaultPackage.path@/@project.className@Command.kt
- cli/features/test-picocli-junit/feature.yml
- cli/features/test-picocli-junit/skeleton/src/test/java/@defaultPackage.path@/@project.className@CommandTest.java
- cli/features/test-picocli-spek/feature.yml
- cli/features/test-picocli-spek/skeleton/src/test/kotlin/@defaultPackage.path@/@project.className@CommandTest.kt
- cli/features/test-picocli-spock/feature.yml
- cli/features/test-picocli-spock/skeleton/src/test/groovy/@defaultPackage.path@/@project.className@CommandSpec.groovy
- cli/skeleton/gradle-build/build.gradle
- cli/skeleton/maven-build/pom.xml
This PR introduces a `create-cli-app` command that generates a cli project with an example command, and sets this command as the main class of the application.
This addresses https://github.com/micronaut-projects/micronaut-core/issues/474.
There is an accompanying PR (https://github.com/micronaut-projects/micronaut-core/pull/480) for the micronaut-core project.
> #474 add create-cli-app command that creates CLI app with the correct main class

- base/features/graal-native-image/skeleton/gradle-build/Dockerfile
- base/features/graal-native-image/skeleton/gradle-build/build-native-image.sh
- base/features/graal-native-image/skeleton/gradle-build/docker-build.sh
- base/features/graal-native-image/skeleton/maven-build/Dockerfile
- base/features/graal-native-image/skeleton/maven-build/build-native-image.sh
- base/features/graal-native-image/skeleton/maven-build/docker-build.sh
- Add scripts to build and run Graal native image using Docker
- Bring back `build-native-image.sh` to create Graal native images without using Docker
This needs to be merged with: https://github.com/micronaut-projects/micronaut-core/pull/779
> Graal improvements

- base/features/java/skeleton/gradle-build/build.gradle
- base/features/java/skeleton/maven-build/pom.xml
I found some encode issue when generated swagger.yml using openapi, so add utf-8 encode to java compile
> Add UTF-8 Encode to JavaCompile

- base/features/spek/feature.yml
Simple typo `framewokr` => `framework`
> Fixed Typo the Spek feature's description

- README.md
- base/features/aws-api-gateway-graal/feature.yml
- base/features/aws-api-gateway-graal/skeleton/README.md
- base/features/aws-api-gateway-graal/skeleton/deploy.sh
- base/features/aws-api-gateway-graal/skeleton/gradle-build/Dockerfile
- base/features/aws-api-gateway-graal/skeleton/gradle-build/build-native-image.sh
- base/features/aws-api-gateway-graal/skeleton/lambda-role-policy.json
- base/features/aws-api-gateway-graal/skeleton/maven-build/Dockerfile
- base/features/aws-api-gateway-graal/skeleton/maven-build/build-native-image.sh
- base/features/aws-api-gateway-graal/skeleton/sam-local.sh
- base/features/aws-api-gateway-graal/skeleton/sam.yaml
- base/features/aws-api-gateway-graal/skeleton/src/main/java/@defaultPackage.path@/ExampleController.java
- base/features/aws-api-gateway-graal/skeleton/src/main/resources/netty-reflect.json
- base/features/aws-api-gateway-graal/skeleton/src/main/resources/reflect.json
Based on recent [experience](https://github.com/micronaut-projects/micronaut-aws/issues/6#issuecomment-463391780) with improving code of graal native compiled micronaut example, here is improvements to micronaut CLI code generation profile:
- Added basic commands for building profiles
- More reflect files
- Added example /ping controller
- Added script for running function locally via sam
- Using the same build-native-image.sh inside Dockerfile
- Trying to read ARN of role to create Lambda with or show error with explanation how to create role
- Improved documentation and dependencies
> Improved aws-api-gateway-graal feature targeting 

- base/features/micrometer-cloudwatch/feature.yml
- base/features/micrometer-cloudwatch/skeleton/src/main/resources/application.yml
Realized that I added support for micrometer cloudwatch in core but did not have a corresponding PR here.
> Adding support for micrometer-cloudwatch feature

- base/features/aws-api-gateway/skeleton/gradle-build/build.gradle
Right now, only compile scoped dependencies/jars are added to to .zip file. 
This will add runtime scoped dependencies/jars to .zip file (e.g.: `runtime "com.fasterxml.jackson.module:jackson-module-kotlin:2.9.8"`)
> Add runtime dependencies to ZIP

- base/features/java/skeleton/maven-build/pom.xml
It's not necessary to set the encoding configuration in the
`maven-compiler-plugin` because it takes the value from
`${project.build.sourceEncoding}` property that is set in file
`micronaut-profiles/base/skeleton/maven-build/pom.xml`
In Maven, configuration by properties use to be the preferred way.
You can see it in the official documentation:
[https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html)
> Remove duplicate Maven encoding configuration

- base/skeleton/maven-build/pom.xml
Like `${project.build.sourceEncoding}` property to set the encoding of the
source code, use to be a good practice in Maven set the property
`${project.reporting.outputEncoding}` that is used by different plugins
(like site plugin) to write their respective reporting outputs.
Some documentation about the property:
https://maven.apache.org/general.html#special-characters-site
> Set encoding for Maven reporting output

- base/features/java/skeleton/maven-build/pom.xml
In Maven is preferred to use the properties `${maven.compiler.source}` and
`${maven.compiler.target}` that are already set in file
`micronaut-profiles/base/skeleton/maven-build/pom.xml`
Maven official documentation:
[https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#source](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#source)
> Remove duplicate Maven compiler 'source' and 'target' version configuration

- base/features/junit/skeleton/maven-build/pom.xml
Remove deprecated `junit-platform-surefire-provider` and configure JUnit 5 following their team recommendations.
[https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven)
> Update junit Maven feature

- configuration/features/java/skeleton/maven-build/pom.xml
I'm sorry but I don't know exactly the purpose of this `pom.xml`, but I think is good idea to
apply the same Maven good practices than in my previous commits, so in Maven
use to be preferred to set the configuration values with properties.
In this commit all the properties used are officially supported by the Maven
compiler plugin
(https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html)
If you told me the purpose of `configuration/` directory and the this `pom.xml` I could try to improve my pull request.
Thanks any way!
> Use properties to configure Maven compiler plugin

- base/features/junit/skeleton/maven-build/pom.xml
- base/features/spek/skeleton/maven-build/pom.xml
- base/features/spock/skeleton/maven-build/pom.xml
The `pluginManagement` is the preferred place to configure the plugins because is like the "metadata" configuration that will be inherited by all children.
Propagate the junit 5 Maven configuration to the other features pom.xml
> Move maven surefire configuration to pluginmanagement

- service/skeleton/Dockerfile
Since JDK 10, "-XX:+UnlockExperimentalVMOptions" and "-XX:+UseCGroupMemoryLimitForHeap" are useless.
> Fix Java 11 option in Dockerfile

- base/features/graal-native-image/skeleton/Dockerfile
-  Create statically linked executable so binary don't need glibc
> Use scratch as base image

- base/features/graal-native-image/skeleton/Dockerfile
I'm reverting the changes done in #183 and switch back to `alpine-glibc`. Now the applications that run in Docker start with `libsunec.so` available.
While trying to deploy a Micronaut app to AWS Lambda as a function I've discovered that if the application calls a 3rd party API using HTTPS, then `libsunec.so` needs to be present or otherwise it doesn't work and the container dies. That currently doesn't work when using `--static` and `scratch` as a base image.
In Graal `20.0.0-dev` they include by default `libsunec`. Actually I build the native-image apps for our test suite now with `--static`. For example, for the JWT security app: https://github.com/micronaut-graal-tests/micronaut-security-jwt-graal/commit/8b3ecd4a42db44cf0882480a4e15a195561a616f
Once GraalVM 20.0.0 is out I'll revisit …
> Switch back to alpine-glibc and include libsunec

- base/features/ehcache/feature.yml
- base/features/ehcache/skeleton/src/main/resources/application.yml
@alvarosanchez question:
in the documentation we have this: https://micronaut-projects.github.io/micronaut-cache/snapshot/guide/#ehcache
it reads that the dependency is `compile 'org.ehcache:ehcache:3.8.0'`. I was thinking it should be `io.micronaut.cache:micronaut-cache-ehcache`, as the ehcache project here has a dependency already to the `'org.ehcache:ehcache:3.8.0'`.
in the profile i declared a dependency upon `io.micronaut.cache:micronaut-cache-ehcache`
> ehcache-profile

- base/features/application/feature.yml
- base/skeleton/gradle-build/gradle/wrapper/gradle-wrapper.properties
- function-aws-alexa/profile.yml
- function-aws/profile.yml
When generating new Micronaut apps gradlew version will now be 6.0.1 as per https://github.com/micronaut-projects/micronaut-core/issues/2347 once this PR has merged.
> updating generative gradle version

- base/features/graal-native-image-kotlin/feature.yml
- base/features/graal-native-image-kotlin/skeleton/Dockerfile
- base/features/graal-native-image-kotlin/skeleton/docker-build.sh
- base/features/graal-native-image-kotlin/skeleton/src/main/resources/META-INF/native-image/@defaultPackage@/@app.name@-application/native-image.properties
- base/features/graal-native-image/feature.yml
- base/features/graal-native-image/skeleton/Dockerfile
This PR should be merged with https://github.com/micronaut-projects/micronaut-core/pull/2418
- Update the profiles to GraalVM 19.3.0
- Create a new feature for Kotlin so `micronaut-graal` is in kapt scope instead of annotationProcessor. This fixes https://github.com/micronaut-projects/micronaut-core/issues/2336
> Update graal to 19.3.0

- base/features/graal-native-image/skeleton/src/main/resources/META-INF/native-image/@defaultPackage@/@app.name@-application/native-image.properties
- cli/profile.yml
- cli/skeleton/gradle-build/build.gradle
- cli/skeleton/maven-build/pom.xml
- function-aws-alexa/profile.yml
- function-aws-alexa/skeleton/gradle-build/build.gradle
- function-aws-alexa/skeleton/maven-build/pom.xml
- function-aws/features/function-aws-groovy/feature.yml
- function-aws/features/function-aws-groovy/skeleton/gradle-build/build.gradle
- function-aws/features/function-aws-groovy/skeleton/maven-build/pom.xml
- function-aws/features/function-aws-java/feature.yml
- function-aws/features/function-aws-java/skeleton/gradle-build/build.gradle
- function-aws/features/function-aws-java/skeleton/maven-build/pom.xml
- function-aws/features/function-aws-kotlin/feature.yml
- function-aws/features/function-aws-kotlin/skeleton/gradle-build/build.gradle
- function-aws/features/function-aws-kotlin/skeleton/maven-build/pom.xml
- function-aws/profile.yml
- grpc/profile.yml
- grpc/skeleton/gradle-build/build.gradle
- grpc/skeleton/maven-build/pom.xml
- kafka/profile.yml
- kafka/skeleton/gradle-build/build.gradle
- kafka/skeleton/maven-build/pom.xml
- profile/profile.yml
- rabbitmq/profile.yml
- rabbitmq/skeleton/gradle-build/build.gradle
- rabbitmq/skeleton/maven-build/pom.xml
- service/profile.yml
- service/skeleton/gradle-build/build.gradle
- service/skeleton/maven-build/pom.xml
Updating how `mainClassName` is set for profiles. `mainClassName` is now specified in either the `profile.yml` or the `feature.yml` or both. If specified in the `feature.yml` it will over ride what is set in the `profile.yml`.
This PR is dependent on core pr https://github.com/micronaut-projects/micronaut-core/pull/2458 DO NOT MERGE WITHOUT DOING BOTH
> Issue 1207 2

- base/features/log4j2/feature.yml
- base/features/log4j2/skeleton/src/main/resources/log4j2.xml
you can now use the log4j2 feature with gradle builds `mn create-app test-app -f log4j2`. This adds the necessary dependencies and the configuration file `log4j2.xml`. The log4j-core dependency needs to be `implementation` otherwise the generated apps will not build.
There is some difference in using log4j2 when building with maven `mn create-app test-app -f log4j2 -b maven`. Everything is generated correctly (correct dependencies and log4j2.xml) and if you do a `./mvnw clean install` you can see that it is using the log4j2 config but when creating a controller and trying to add logging it does not behave the same way as it does when built with gradle. In example when building with gradle and adding a logger to the controller this import works `import org.apache.logging.log4j.Logger;` but …
> adding ability to select log4j2 feature when using gradle

- function/features/openfaas/skeleton/function.yml
According to the documentation, the provider name should be `openfaas` and not `faas`: https://docs.openfaas.com/reference/yaml/
> Provider.name should be "openfaas" instead of "faas"

- function-aws-alexa/profile.yml
- function-aws/profile.yml
this version no longer have issues when AWS credentials are not set
> Upgraded AWS Gradle plugin
