base/features/jrebel/feature.yml, base/features/jrebel/skeleton/gradle-build/build.gradle, base/features/jrebel/skeleton/gradle-build/gradle.properties, base/features/jrebel/skeleton/maven-build/pom.xml, base/features/springloaded/feature.yml, base/features/springloaded/skeleton/gradle-build/build.gradle, base/features/springloaded/skeleton/gradle-build/gradle.properties, base/profile.yml, base/skeleton/gradle-build/build.gradle, base/skeleton/maven-build/pom.xml, service/profile.yml
Adds features for Spring-Loaded and JRebel.
=> Reloading features

kafka/build.gradle, kafka/commands/create-kafka-listener.groovy, kafka/commands/create-kafka-producer.groovy, kafka/profile.yml, kafka/skeleton/src/main/resources/application.yml, kafka/templates/groovy/Listener.groovy, kafka/templates/groovy/Producer.groovy, kafka/templates/java/Listener.java, kafka/templates/java/Producer.java, kafka/templates/kotlin/Listener.kt, kafka/templates/kotlin/Producer.kt, settings.gradle
To include dependency/config for Kafka to a service app:
```
mn create-app my-kafka-app --features kafka
```
To create a Kafka messaging service: 
```
mn create-app my-kafka-app --profile kafka
```
```
mn create-kafka-producer Item
| Rendered template Producer.java to destination src/main/java/my/kafka/app/ItemProducer.java
```
```
package my.kafka.app;
import io.micronaut.configuration.kafka.annotation.KafkaClient;
@KafkaClient
public interface ItemProducer {
}
```
```
mn  create-kafka-producer OrderProducer -lang groovy
| Rendered template Producer.groovy to destination src/main/groovy/my/kafka/app/OrderProducer.groovy
```
```
import io.micronaut.configuration.kafka.annotation.KafkaClient
@KafkaClient
interface OrderProducer {
}
```
```
mn create-kafka-listener Order -lang kotlin
| …
```
=> Added kafka feature & profile

base/features/picocli/feature.yml, cli/build.gradle, cli/commands/create-command.groovy, cli/profile.yml, cli/skeleton/gradle-build/build.gradle, cli/skeleton/maven-build/pom.xml, cli/skeleton/src/main/resources/application.yml, cli/templates/groovy/Command.groovy, cli/templates/groovy/CommandSpec.groovy, cli/templates/java/Command.java, cli/templates/java/CommandTest.java, cli/templates/kotlin/Command.kt, cli/templates/kotlin/CommandTest.kt, settings.gradle
Please take a look at this PR for https://github.com/micronaut-projects/micronaut-core/issues/330 adding a picocli profile CLI applications.
=> #330 picocli profile

cli/templates/groovy/Command.groovy, cli/templates/groovy/CommandSpec.groovy, cli/templates/java/Command.java, cli/templates/java/CommandTest.java, cli/templates/kotlin/Command.kt, cli/templates/kotlin/CommandTest.kt
#330 improvements: 
* reduce boilerplate in generated code (delegate to new PicocliRunner class)
* added Spek test for kotlin
=> #330 improvements: reduce boilerplate in generated code

cli/skeleton/gradle-build/build.gradle
Fixes https://github.com/micronaut-projects/micronaut-core/issues/497
=> Remove empty jvmArgs

base/features/annotation-api/feature.yml, base/features/graal-native-image/feature.yml, base/features/hibernate-gorm/feature.yml, base/features/jdbc-dbcp/feature.yml, base/features/jdbc-hikari/feature.yml, base/features/jdbc-tomcat/feature.yml, base/features/neo4j-bolt/feature.yml, base/features/spock/feature.yml, base/features/tracing-jaeger/feature.yml, base/features/tracing-zipkin/feature.yml
This PR must be merged with https://github.com/micronaut-projects/micronaut-core/pull/744
=> Remove versions from dependencies existing in BOM

base/features/graal-native-image/skeleton/gradle-build/Dockerfile, base/features/graal-native-image/skeleton/gradle-build/build-native-image.sh, base/features/graal-native-image/skeleton/maven-build/Dockerfile, base/features/graal-native-image/skeleton/maven-build/build-native-image.sh
This needs to be merged with https://github.com/micronaut-projects/micronaut-core/pull/816
=> Fix support for Graal and Consul

base/features/graal-native-image/skeleton/gradle-build/build-native-image.sh, base/features/graal-native-image/skeleton/maven-build/build-native-image.sh
This needs to be merged with https://github.com/micronaut-projects/micronaut-core/pull/1220
=> Use service loaders in Graal native image generation

function-aws/features/test-aws-junit/skeleton/src/test/java/@defaultPackage.path@/@project.className@Client.java, function-aws/features/test-aws-junit/skeleton/src/test/java/@defaultPackage.path@/@project.className@FunctionTest.java, function-aws/features/test-aws-spek/skeleton/src/test/kotlin/@defaultPackage.path@/@project.className@Client.kt, function-aws/features/test-aws-spek/skeleton/src/test/kotlin/@defaultPackage.path@/@project.className@FunctionTest.kt
Fixes https://github.com/micronaut-projects/micronaut-profiles/issues/127
=> Fix failing test in aws-function profile

base/features/cassandra/skeleton/src/main/resources/application.yml, base/features/elasticsearch/skeleton/src/main/resources/application.yml, base/features/graphql/skeleton/src/main/resources/application.yml, base/features/kafka/skeleton/src/main/resources/application.yml, base/features/micrometer-atlas/skeleton/src/main/resources/application.yml, base/features/micrometer-graphite/skeleton/src/main/resources/application.yml, base/features/micrometer-prometheus/skeleton/src/main/resources/application.yml, base/features/micrometer-statsd/skeleton/src/main/resources/application.yml, base/features/micrometer/skeleton/src/main/resources/application.yml, base/features/mongo-reactive/skeleton/src/main/resources/application.yml, base/features/netflix-ribbon/skeleton/src/main/resources/application.yml, base/features/postgres-reactive/skeleton/src/main/resources/application.yml, base/features/rabbitmq/skeleton/src/main/resources/application.yml, base/features/redis-lettuce/skeleton/src/main/resources/application.yml, cli/skeleton/src/main/resources/application.yml, function-aws-alexa/skeleton/src/main/resources/application.yml, function/skeleton/src/main/resources/application.yml, service/skeleton/src/main/resources/application.yml
Normalize indentation of all `application.yml` files to 2 spaces
=> Yaml files are indented with 2 spaces

rabbitmq/profile.yml
* Add application feature to RabbitMQ profile.
=> Updated RabbitMQ profile as per changes in application feature

base/features/aws-api-gateway/skeleton/gradle-build/build.gradle
=> Include annotation processed classes into ZIP in aws-api-gateway + kotlin

cli/features/picocli-groovy/feature.yml, cli/features/picocli-java/feature.yml, cli/features/picocli-kotlin/feature.yml
This PR needs to be merged with https://github.com/micronaut-projects/micronaut-core/pull/1573
=> Delete main Application file for cli apps. Fixes #138

gradle.properties, service/templates/groovy/ControllerSpec.groovy
Cleanup controller client injection as requested from James
=> Controllertestfix

cli/features/picocli-groovy/feature.yml, cli/features/picocli-java/feature.yml, cli/features/picocli-kotlin/feature.yml, cli/profile.yml
After discussing with James we'll use `skeleton.excludes`.
=> Use skeleton.excludes for files that need to be deleted. Fixes #138

base/features/aws-api-gateway-graal/skeleton/Dockerfile, base/features/graal-native-image/skeleton/Dockerfile
**This needs to be merged with** https://github.com/micronaut-projects/micronaut-core/pull/1674
=> Upgrade to Graal 19.0.0

base/features/micrometer-appoptics/feature.yml, base/features/micrometer-appoptics/skeleton/src/main/resources/application.yml, base/features/micrometer-azure-monitor/feature.yml, base/features/micrometer-azure-monitor/skeleton/src/main/resources/application.yml, base/features/micrometer-datadog/feature.yml, base/features/micrometer-datadog/skeleton/src/main/resources/application.yml, base/features/micrometer-dynatrace/feature.yml, base/features/micrometer-dynatrace/skeleton/src/main/resources/application.yml, base/features/micrometer-elastic/feature.yml, base/features/micrometer-elastic/skeleton/src/main/resources/application.yml, base/features/micrometer-ganglia/feature.yml, base/features/micrometer-ganglia/skeleton/src/main/resources/application.yml, base/features/micrometer-humio/feature.yml, base/features/micrometer-humio/skeleton/src/main/resources/application.yml, base/features/micrometer-influx/feature.yml, base/features/micrometer-influx/skeleton/src/main/resources/application.yml, base/features/micrometer-jmx/feature.yml, base/features/micrometer-jmx/skeleton/src/main/resources/application.yml, base/features/micrometer-kairos/feature.yml, base/features/micrometer-kairos/skeleton/src/main/resources/application.yml, base/features/micrometer-new-relic/feature.yml, base/features/micrometer-new-relic/skeleton/src/main/resources/application.yml, base/features/micrometer-signalfx/feature.yml, base/features/micrometer-signalfx/skeleton/src/main/resources/application.yml, base/features/micrometer-stackdriver/feature.yml, base/features/micrometer-stackdriver/skeleton/src/main/resources/application.yml, base/features/micrometer-wavefront/feature.yml, base/features/micrometer-wavefront/skeleton/src/main/resources/application.yml
Per @ilopmar request, adding the features for all the micrometer metric registries added in the last few pull requests.
This PR should be merged after the following PR is approved and merged as it includes the last micrometer metric registers: https://github.com/micronaut-projects/micronaut-micrometer/pull/20
=> Micronaut features for new micrometer metric registries

base/features/kubernetes/feature.yml, base/features/kubernetes/skeleton/k8s.yml, base/features/kubernetes/skeleton/src/main/resources/bootstrap.yml
Fixes: https://github.com/micronaut-projects/micronaut-kubernetes/issues/30
=> Kubernetes feature

base/features/aws-api-gateway-graal/skeleton/Dockerfile, base/features/aws-api-gateway-graal/skeleton/bootstrap
this allows connecting to PostrgreSQL running inside VPC and probably to other services using the secured connection as well.
see https://medium.com/agorapulse-stories/how-to-support-secured-connections-inside-micronauts-graalvm-730800d2ed03
=> Added libsunec.so to the function bundle

base/features/aws-api-gateway-graal/skeleton/deploy.sh
Since this has some BASH syntax I'd suggest we change the
=> Changes default runner to bash

base/features/vertx-mysql-client/feature.yml, base/features/vertx-mysql-client/skeleton/src/main/resources/application.yml, base/features/vertx-pg-client/feature.yml, base/features/vertx-pg-client/skeleton/src/main/resources/application.yml
=> Add profiles for the Reactive SQL Client

base/features/hazelcast/feature.yml, base/features/hazelcast/skeleton/src/main/resources/application.yml
this contributes to https://github.com/micronaut-projects/micronaut-cache/issues/13
=> hazelcast feature

grpc/profile.yml
This will resolve https://github.com/micronaut-projects/micronaut-core/issues/2451
Also protobuf plugin versions `0.8.8, 0.8.9` would also remedy this issue
=> upgrading grpc protobuf plugin dependency to version 0.8.10

base/features/jib/feature.yml
version 0.9.9 it's one year old and currently version 1.8.0 has been released
=> update jib to 1.8.0

base/features/aws-api-gateway-graal/skeleton/deploy.sh
=> Checking whether the function exists to update the code instead.

base/features/aws-api-gateway-graal/skeleton/Dockerfile, base/features/graal-native-image-kotlin/skeleton/Dockerfile, base/features/graal-native-image/skeleton/Dockerfile
Upgrade GraalVM to 19.3.1. Fixes https://github.com/micronaut-projects/micronaut-profiles/issues/209
=> Upgrade GraalVM to 19.3.1

base/features/graal-native-image/skeleton/Dockerfile
Fixes https://github.com/micronaut-projects/micronaut-core/issues/2713
=> Reorder Dockerfile for GraalVM

base/features/aws-api-gateway-graal/skeleton/Dockerfile
Close: https://github.com/micronaut-projects/micronaut-profiles/issues/232
=> Update Dockerfile for aws-api-gateway-graal

README.md, base/features/junit/feature.yml, base/features/kotlin/skeleton/maven-build/pom.xml, base/features/kotlintest/feature.yml, base/features/spock/feature.yml, build.gradle
Fixes: 
* https://github.com/micronaut-projects/micronaut-test/issues/90
* https://github.com/micronaut-projects/micronaut-test/issues/109
=> Using evictions to only have one test framework

base/features/application/skeleton/gradle-build/build.gradle
fixes https://github.com/micronaut-projects/micronaut-core/issues/2765
=> settings applied to all run tasks (run and runShadow)
